# handlers file for .
- name: Restart Postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: restarted

- name: Start Postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: Enable Postgresql
  ansible.builtin.systemd:
    name: postgresql
    enabled: true

- name: Restart sonar
  ansible.builtin.service:
    name: sonar
    state: restarted

- name: Start sonar
  ansible.builtin.service:
    name: sonar
    state: started
    enabled: true
